name: product_approval_dashboard
description: kelem product approval dashbaord

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.5.0
  firebase_auth: ^3.0.2
  google_sign_in: ^5.0.7
  cloud_firestore: ^2.3.0
  fluttertoast: ^8.0.7
  firebase_storage: ^10.0.0
  flutter_spinkit: 5.1.0
  uuid: ^3.0.4
  image_picker_web: ^2.0.3
  firebase: ^9.0.1
  mime_type: ^1.0.0
  path: ^1.8.0
  http: ^0.13.3
  intl: ^0.17.0
  simple_tags: 0.0.4
  shared_preferences: ^2.0.7
  simple_autocomplete_formfield: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/google_signin_btn.png
    - assets/images/working.png
    - assets/images/no_data_found.png
    - assets/images/image_folder.png
    - assets/images/baby_miki.png

  fonts:
    - family: Sofia Pro
      fonts:
        - asset: assets/fonts/Sofia Pro Regular.ttf

